package librarysystem.entities;
// Generated Jul 20, 2017 12:35:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Librarian generated by hbm2java
 */
public class Librarian  implements java.io.Serializable {


     private int id;
     private Library library;
     private Role role;
     private String name;
     private Set tasks = new HashSet(0);

    public Librarian() {
    }

	
    public Librarian(int id, Library library, Role role, String name) {
        this.id = id;
        this.library = library;
        this.role = role;
        this.name = name;
    }

    public Librarian(Library library, Role role, String name) {
        this.library = library;
        this.role = role;
        this.name = name;
    }
    
    public Librarian(int id, Library library, Role role, String name, Set tasks) {
       this.id = id;
       this.library = library;
       this.role = role;
       this.name = name;
       this.tasks = tasks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Library getLibrary() {
        return this.library;
    }
    
    public void setLibrary(Library library) {
        this.library = library;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


