package librarysystem.entities;
// Generated Jul 20, 2017 12:35:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private int id;
     private String name;
     private Set librarians = new HashSet(0);

    public Task() {
    }

	
    public Task(int id, String name) {
        this.id = id;
        this.name = name;
    }
    
    public Task(String name) {
       this.name = name;
    }
    
    public Task(int id, String name, Set librarians) {
       this.id = id;
       this.name = name;
       this.librarians = librarians;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLibrarians() {
        return this.librarians;
    }
    
    public void setLibrarians(Set librarians) {
        this.librarians = librarians;
    }




}


